import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";

const geistPoppins = Poppins({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Resto Sedap Mantap",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistPoppins.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
